update ci.yaml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,63 +8,41 @@ on:
   workflow_dispatch:
 
 jobs:
-  frontend-vulnerability-check:
-    name: Frontend
-    uses: ./.github/workflows/frontend-vulnerability-check.yml
-
-  backend-vulnerability-check:
-    name: Backend
-    uses: ./.github/workflows/backend-vulnerability-check.yml
-
-  backend-sast-check:
-    name: Backend
-    uses: ./.github/workflows/backend-sast-check.yml
-
   frontend-lint-format-check:
-    name: Frontend
-    needs: frontend-vulnerability-check
+    name: Frontend lint
     uses: ./.github/workflows/frontend-lint-format-check.yml
 
   backend-lint-format-check:
-    name: Backend
-    needs: [backend-vulnerability-check, backend-sast-check]
+    name: Backend lint
     uses: ./.github/workflows/backend-lint-format-check.yml
 
-  dast-check:
-    name: Backend
-    needs: backend-lint-format-check
-    uses: ./.github/workflows/dast-scan.yml
-    secrets: inherit
-
   frontend-unit-tests:
-    name: Frontend
+    name: Frontend tests
     needs: frontend-lint-format-check
     uses: ./.github/workflows/frontend-unit-tests.yml
 
   backend-unit-tests:
-    name: Backend
+    name: Backend tests
     needs: backend-lint-format-check
     uses: ./.github/workflows/backend-unit-tests.yml
 
-  backend-integration-tests:
-    name: Backend
-    needs: backend-unit-tests
-    uses: ./.github/workflows/backend-integration-tests.yml
-
-  e2e-tests:
-    name: E2E
-    needs: [frontend-unit-tests, backend-integration-tests]
-    uses: ./.github/workflows/e2e-tests.yml
-
-  frontend-build:
-    name: Frontend
-    needs: [e2e-tests, dast-check]
-    uses: ./.github/workflows/frontend-build.yml
-
   pipeline-success:
     name: Pipeline success
-    needs: frontend-build
+    needs:
+      [
+        frontend-lint-format-check,
+        backend-lint-format-check,
+        frontend-unit-tests,
+        backend-unit-tests,
+      ]
     runs-on: ubuntu-latest
-    if: success()
+    if: always()
     steps:
-      - run: echo "Pipeline completed successfully!"
+      - name: Pipeline succeeded
+        if: "!contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')"
+        run: echo "All checks passed successfully!"
+      - name: Pipeline failed
+        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+        run: |
+          echo "Some checks failed or were cancelled."
+          exit 1
